{% set name = "geohexgrid" %}
{% set version = "2.1.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 45902dc3c18720724f57dfa83371f549ad84768dafed2f9c3ce5b562c639f127

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - geopandas >=0.11.1

test:
  imports:
    - geohexgrid
  requires:
    - python {{ python_min }}
    - geopandas
    - numpy
    - pip
    - pytest
    - shapely
  source_files:
    - tests
  commands:
    - pip check
    - python -m pytest tests

about:
  home: https://github.com/mrcagney/geohexgrid
  summary: A Python library for making geographic flat-top hexagon grids like QGIS's `create grid` function
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - christophfink
